### ISSUE TITLE
Details of the parse_filepath() vuln?

### ISSUE THREAD

**Issue by Endoisshy** [cscosu/ctf-writeups#2]
Can you provide more detail about where you saw this function and how it lead you to finding the vulnerability? Following your write up the vulnerability itself makes sense, but where did you find this?

**Comment by qxxxb** [comment]
I updated the write-up a bit show where the [vulnerable function](https://github.com/cscosu/ctf-writeups/blob/master/2021/def_con_quals/nooopster/ghidra.mp4) is
